# Generated by Django 5.0.1 on 2024-01-17 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_name', models.CharField(max_length=100, unique=True)),
                ('make_Image', models.ImageField(blank=True, null=True, upload_to='make_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Fueltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('model_Image', models.ImageField(blank=True, null=True, upload_to='model_images/')),
                ('make_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='ModelVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torque', models.CharField(max_length=50)),
                ('bhp', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('tyre_size', models.CharField(max_length=50)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.fueltype')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicleinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_Regno', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.modelvariant')),
            ],
        ),
    ]
