# Generated by Django 5.0.1 on 2024-02-02 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_servicecenter_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.servicecenter')),
                ('service_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
