# Generated by Django 5.0.1 on 2024-01-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_carmake_fueltype_carmodel_modelvariant_userinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvariant',
            name='variant_name',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='modelvariant',
            unique_together={('model', 'variant_name')},
        ),
    ]
