# Generated by Django 5.0.1 on 2024-02-04 11:41

from django.db import migrations, models
from django.utils.text import slugify
def generate_slugs(apps, schema_editor):
    User = apps.get_model('client', 'User')
    for user in User.objects.all():
        user.slug = slugify(user.email)
        user.save()


class Migration(migrations.Migration):
    
    dependencies = [
        ('client', '0003_servicemanagers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True),

        ),
         migrations.RunPython(generate_slugs),
    ]
