# Generated by Django 5.0.1 on 2024-01-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_carmake_carmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmake',
            old_name='name',
            new_name='make_name',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='Model_Image',
            new_name='model_Image',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='name',
            new_name='model_name',
        ),
    ]
