# Generated by Django 5.0.1 on 2024-01-16 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_name_carmake_make_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicleinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_Regno', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('ng', 'Natural Gas'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=50)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.carmodel')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
