# Generated by Django 5.0.1 on 2024-02-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.manager'),
        ),
        migrations.DeleteModel(
            name='ServiceManagers',
        ),
    ]
