# Generated by Django 5.0.1 on 2024-01-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_modelvariant_variant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='transmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
