# Generated by Django 5.0.1 on 2024-02-05 16:51

from django.db import migrations, models
from django.utils.text import slugify

def add_service_center_slugs(apps, schema_editor):
    ServiceCenter = apps.get_model('client', 'ServiceCenter')
    for service_center in ServiceCenter.objects.all():
        if not service_center.slug:
            base_slug = slugify(f"{service_center.place}-{service_center.city}")
            unique_slug = base_slug
            counter = 1
            while ServiceCenter.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1
            service_center.slug = unique_slug
            service_center.save()

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_servicecenter_manager_delete_servicemanagers'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.RunPython(add_service_center_slugs, reverse_code=migrations.RunPython.noop),
    ]
