# Generated by Django 5.0.1 on 2024-01-16 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_vehicleinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinfo',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
