# Generated by Django 5.0.1 on 2024-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_servicecenter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
