# Generated by Django 5.0.1 on 2024-02-07 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_servicecenter_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='mechanicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.servicecenter')),
            ],
        ),
    ]
