# Generated by Django 5.0.1 on 2024-01-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_servicecenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
