# Generated by Django 5.0.1 on 2024-02-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_mechaniclist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotname', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('ALLOCATED', 'Allocated')], default='FREE', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('allocated_mech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.servicecenter')),
            ],
        ),
    ]
