# Generated by Django 5.0.1 on 2024-01-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_servicecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
