# Generated by Django 5.0.1 on 2024-02-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_servicesslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesslots',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=50),
        ),
    ]
