# Generated by Django 5.0.1 on 2024-02-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_servicesslots_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesslots',
            name='allocated_mech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='servicesslots',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=50),
        ),
    ]
