# Generated by Django 5.0.1 on 2024-02-11 16:35

from django.db import migrations, models
from django.utils.text import slugify

def populate_slug(apps, schema_editor):
    CarMake = apps.get_model('client', 'CarMake')
    CarModel = apps.get_model('client', 'CarModel')

    for car_make in CarMake.objects.all():
        car_make.make_slug = slugify(car_make.make_name)
        car_make.save()

    for car_model in CarModel.objects.all():
        car_model.model_slug = slugify(car_model.model_name)
        car_model.save()

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_remove_vehicleinfo_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmake',
            name='make_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
         migrations.RunPython(populate_slug),
    ]
