# Generated by Django 5.0.1 on 2024-02-11 16:40

from django.db import migrations, models
from django.utils.text import slugify

def populate_variant_slug(apps, schema_editor):
    ModelVariant = apps.get_model('client', 'ModelVariant')

    for variant in ModelVariant.objects.all():
        variant.variant_slug = slugify(f"{variant.model.model_name}-{variant.variant_name}")
        variant.save()

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_carmake_make_slug_carmodel_model_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvariant',
            name='variant_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(populate_variant_slug),
    ]
