# Generated by Django 5.0.1 on 2024-02-21 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_serviceorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('service_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.servicelist')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.serviceorder')),
                ('vehicle_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.vehicleinfo')),
            ],
            options={
                'unique_together': {('service_order', 'vehicle_info', 'service_list')},
            },
        ),
    ]
