# Generated by Django 5.0.1 on 2024-02-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_serviceorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderitem',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
    ]
