# Generated by Django 5.0.1 on 2024-02-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_alter_serviceorderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('on hold', 'On hold'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='on hold', max_length=20),
        ),
    ]
