# Generated by Django 5.0.1 on 2024-02-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_roadsideassistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsideassistance',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
