# Generated by Django 5.0.1 on 2024-02-27 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_alter_roadsideassistance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='service_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.servicesslots'),
        ),
    ]
