# Generated by Django 5.0.1 on 2024-03-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_task_servicelist_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
