# Generated by Django 5.0.1 on 2024-03-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_serviceorder_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
