# Generated by Django 5.0.1 on 2024-03-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_alter_serviceorder_status_alter_vehicleinfo_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsideassistance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,),
            preserve_default=False,
        ),
    ]
