# Generated by Django 5.0.1 on 2024-03-23 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_alter_roadsideassistance_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicerecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recslug', models.SlugField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('service_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.servicelist')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.serviceorder')),
            ],
            options={
                'unique_together': {('service_order', 'service_list')},
            },
        ),
    ]
