# Generated by Django 5.0.1 on 2024-04-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0038_serviceorderitem_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorderitem',
            name='service_type',
        ),
    ]
