# Generated by Django 5.0.1 on 2024-04-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0040_serviceorder_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsideassistance',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.serviceorder'),
        ),
    ]
